version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: pricing
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
  redis:
    image: redis:7.2
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: ["start-dev", "--import-realm"]
    ports:
      - "81:8080"
    volumes:
      - ./docker/pricing-realm.json:/opt/keycloak/data/import/pricing-realm.json:ro
volumes:
  postgres_data:
  pgadmin_data:
  redis_data:
