spring.application.name=QuotationAgent
spring.web.mvc.servlet.path=/api
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5435/quotation_agent
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.ai.ollama.chat.options.model=mistral
spring.ai.ollama.chat.options.temperature=0.1
spring.ai.ollama.init.pull-model-strategy=always

# https://docs.spring.io/spring-cloud-stream/reference/spring-cloud-stream/binding-properties.html
spring.cloud.stream.default.group=quotation-agent-group
spring.cloud.function.definition=onProduct;onProductAggregated
spring.cloud.stream.bindings.onQuotationSucceeded-in-0.destination=pricing-quotation-succeeded.v1
spring.cloud.stream.bindings.onQuotationSucceeded-in-0.error-handler-definition=onQuotationSucceededError
spring.cloud.stream.rabbit.bindings.onQuotationSucceeded-in-0.consumer.auto-bind-dlq=true
spring.cloud.stream.bindings.onProductAggregated-in-0.destination=pricing-product-aggregated.v1
spring.cloud.stream.bindings.onProductAggregated-in-0.error-handler-definition=onProductAggregatedError
