spring.application.name=QuotationAgent
spring.web.mvc.servlet.path=/api
server.port=8085
spring.datasource.url=jdbc:postgresql://localhost:5435/quotation_agent
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.ai.ollama.chat.options.model=mistral
spring.ai.ollama.chat.options.temperature=0.1
spring.ai.ollama.init.pull-model-strategy=always
spring.ai.vectorstore.milvus.initialize-schema=true
spring.ai.vectorstore.milvus.client.host=localhost
spring.ai.vectorstore.milvus.client.port=19530
spring.ai.vectorstore.milvus.client.username=root
spring.ai.vectorstore.milvus.client.password=milvus
spring.ai.vectorstore.milvus.databaseName=default
spring.ai.vectorstore.milvus.collectionName=vector_store
spring.ai.vectorstore.milvus.embeddingDimension=1024
spring.ai.vectorstore.milvus.indexType=IVF_FLAT
spring.ai.vectorstore.milvus.metricType=COSINE

# Swagger UI OAuth2 Configuration
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.oauth.client-id=quotation-agent-client
springdoc.swagger-ui.oauth.client-secret=quotation-agent-secret
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=false
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/pricing

# OpenTelemetry Configuration
otel.service.name=${spring.application.name}
otel.exporter.otlp.endpoint=http://localhost:4318
otel.exporter.otlp.protocol=http/protobuf
otel.traces.exporter=otlp
otel.metrics.exporter=otlp
otel.logs.exporter=none
management.tracing.sampling.probability=1.0
management.metrics.distribution.percentiles-histogram.http.server.requests=true

# https://docs.spring.io/spring-cloud-stream/reference/spring-cloud-stream/binding-properties.html
spring.cloud.stream.default.group=quotation-agent-group
spring.cloud.function.definition=onProductCreated;onQuotationSubmitted;onQuotationSubmittedError;onQuotationUpdated
spring.cloud.stream.bindings.onQuotationSubmitted-in-0.destination=pricing-quotation-submitted.v1
spring.cloud.stream.bindings.onQuotationSubmitted-in-0.error-handler-definition=onQuotationSubmittedError
spring.cloud.stream.rabbit.bindings.onQuotationSubmitted-in-0.consumer.auto-bind-dlq=true
spring.cloud.stream.bindings.onProductCreated-in-0.destination=pricing-product-created.v1
spring.cloud.stream.bindings.onProductCreated-in-0.error-handler-definition=onProductCreatedError
spring.cloud.stream.rabbit.bindings.onProductCreated-in-0.consumer.auto-bind-dlq=true
spring.cloud.stream.bindings.onQuotationUpdated-in-0.destination=pricing-quotation-updated.v1

application.services.quotation-parser.stub.enabled=true


