spring.application.name=QuotationAgent
spring.web.mvc.servlet.path=/api
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5435/quotation_agent
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.ai.ollama.chat.options.model=mistral
spring.ai.ollama.chat.options.temperature=0.1
spring.ai.ollama.init.pull-model-strategy=always
spring.ai.vectorstore.milvus.initialize-schema=true
spring.ai.vectorstore.milvus.client.host=localhost
spring.ai.vectorstore.milvus.client.port=19530
spring.ai.vectorstore.milvus.client.username=root
spring.ai.vectorstore.milvus.client.password=milvus
spring.ai.vectorstore.milvus.databaseName=default
spring.ai.vectorstore.milvus.collectionName=vector_store
spring.ai.vectorstore.milvus.embeddingDimension=1024
spring.ai.vectorstore.milvus.indexType=IVF_FLAT
spring.ai.vectorstore.milvus.metricType=COSINE
#spring.cache.type=redis
#spring.redis.host=localhost
#spring.redis.port=6379
#spring.security.oauth2.client.registration.keycloak.client-id=quotation-agent-client
#spring.security.oauth2.client.registration.keycloak.client-secret=quotation-agent-secret
#spring.security.oauth2.client.registration.keycloak.provider=keycloak
#spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
#spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/keycloak
#spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
#spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:81/realms/pricing
#spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:81/realms/pricing

# https://docs.spring.io/spring-cloud-stream/reference/spring-cloud-stream/binding-properties.html
spring.cloud.stream.default.group=quotation-agent-group
spring.cloud.function.definition=onProductCreated;onQuotationSubmitted
spring.cloud.stream.bindings.onQuotationSubmitted-in-0.destination=pricing-quotation-submitted.v1
spring.cloud.stream.bindings.onQuotationSubmitted-in-0.error-handler-definition=onQuotationSubmittedError
spring.cloud.stream.rabbit.bindings.onQuotationSubmitted-in-0.consumer.auto-bind-dlq=true
spring.cloud.stream.bindings.onProductCreated-in-0.destination=pricing-product-created.v1
spring.cloud.stream.bindings.onProductCreated-in-0.error-handler-definition=onProductCreatedError
spring.cloud.stream.rabbit.bindings.onProductCreated-in-0.consumer.auto-bind-dlq=true

application.services.quotation-parser.stub.enabled=true


