spring.application.name=QuotationAgent
spring.ai.ollama.chat.options.model=mistral
spring.ai.ollama.chat.options.temperature=0.1
spring.ai.ollama.init.pull-model-strategy=always
spring.ai.vectorstore.milvus.initialize-schema=true
spring.ai.vectorstore.milvus.client.host=localhost
spring.ai.vectorstore.milvus.client.port=19530
spring.ai.vectorstore.milvus.client.username=root
spring.ai.vectorstore.milvus.client.password=milvus
spring.ai.vectorstore.milvus.databaseName=default
spring.ai.vectorstore.milvus.collectionName=vector_store_it
spring.ai.vectorstore.milvus.embeddingDimension=1024
spring.ai.vectorstore.milvus.indexType=IVF_FLAT
spring.ai.vectorstore.milvus.metricType=COSINE
logging.level.com.nviaud.pricing=DEBUG
