spring.application.name=ProductViewer
server.port=8083
spring.web.mvc.servlet.path=/api

# API Versioning Configuration
spring.web.mvc.version.strategy=header
spring.web.mvc.version.param-name=X-API-Version
spring.datasource.url=jdbc:postgresql://localhost:5433/product_viewer
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/pricing

# OpenTelemetry Configuration
otel.service.name=product-admin
otel.exporter.otlp.endpoint=http://localhost:4318
otel.exporter.otlp.protocol=http/protobuf
otel.traces.exporter=otlp
otel.metrics.exporter=otlp
otel.logs.exporter=none
management.tracing.sampling.probability=1.0
management.metrics.distribution.percentiles-histogram.http.server.requests=true

# https://docs.spring.io/spring-cloud-stream/reference/spring-cloud-stream/binding-properties.html
spring.cloud.function.definition=
spring.cloud.stream.default.group=product-admin-group
